/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoSalonRouteImport } from './routes/demo.salon'
import { Route as DemoRestaurantRouteImport } from './routes/demo.restaurant'
import { Route as DemoRealestateRouteImport } from './routes/demo.realestate'
import { Route as DemoHealthRouteImport } from './routes/demo.health'
import { Route as DemoGalleryRouteImport } from './routes/demo.gallery'
import { Route as DemoFitnessRouteImport } from './routes/demo.fitness'
import { Route as DemoEducationRouteImport } from './routes/demo.education'
import { Route as DemoEcommerceRouteImport } from './routes/demo.ecommerce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSalonRoute = DemoSalonRouteImport.update({
  id: '/demo/salon',
  path: '/demo/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRestaurantRoute = DemoRestaurantRouteImport.update({
  id: '/demo/restaurant',
  path: '/demo/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRealestateRoute = DemoRealestateRouteImport.update({
  id: '/demo/realestate',
  path: '/demo/realestate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHealthRoute = DemoHealthRouteImport.update({
  id: '/demo/health',
  path: '/demo/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGalleryRoute = DemoGalleryRouteImport.update({
  id: '/demo/gallery',
  path: '/demo/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFitnessRoute = DemoFitnessRouteImport.update({
  id: '/demo/fitness',
  path: '/demo/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEducationRoute = DemoEducationRouteImport.update({
  id: '/demo/education',
  path: '/demo/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEcommerceRoute = DemoEcommerceRouteImport.update({
  id: '/demo/ecommerce',
  path: '/demo/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/ecommerce': typeof DemoEcommerceRoute
  '/demo/education': typeof DemoEducationRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/gallery': typeof DemoGalleryRoute
  '/demo/health': typeof DemoHealthRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/demo/salon': typeof DemoSalonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/ecommerce': typeof DemoEcommerceRoute
  '/demo/education': typeof DemoEducationRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/gallery': typeof DemoGalleryRoute
  '/demo/health': typeof DemoHealthRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/demo/salon': typeof DemoSalonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/ecommerce': typeof DemoEcommerceRoute
  '/demo/education': typeof DemoEducationRoute
  '/demo/fitness': typeof DemoFitnessRoute
  '/demo/gallery': typeof DemoGalleryRoute
  '/demo/health': typeof DemoHealthRoute
  '/demo/realestate': typeof DemoRealestateRoute
  '/demo/restaurant': typeof DemoRestaurantRoute
  '/demo/salon': typeof DemoSalonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/ecommerce'
    | '/demo/education'
    | '/demo/fitness'
    | '/demo/gallery'
    | '/demo/health'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/demo/salon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/ecommerce'
    | '/demo/education'
    | '/demo/fitness'
    | '/demo/gallery'
    | '/demo/health'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/demo/salon'
  id:
    | '__root__'
    | '/'
    | '/demo/ecommerce'
    | '/demo/education'
    | '/demo/fitness'
    | '/demo/gallery'
    | '/demo/health'
    | '/demo/realestate'
    | '/demo/restaurant'
    | '/demo/salon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoEcommerceRoute: typeof DemoEcommerceRoute
  DemoEducationRoute: typeof DemoEducationRoute
  DemoFitnessRoute: typeof DemoFitnessRoute
  DemoGalleryRoute: typeof DemoGalleryRoute
  DemoHealthRoute: typeof DemoHealthRoute
  DemoRealestateRoute: typeof DemoRealestateRoute
  DemoRestaurantRoute: typeof DemoRestaurantRoute
  DemoSalonRoute: typeof DemoSalonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/salon': {
      id: '/demo/salon'
      path: '/demo/salon'
      fullPath: '/demo/salon'
      preLoaderRoute: typeof DemoSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/restaurant': {
      id: '/demo/restaurant'
      path: '/demo/restaurant'
      fullPath: '/demo/restaurant'
      preLoaderRoute: typeof DemoRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/realestate': {
      id: '/demo/realestate'
      path: '/demo/realestate'
      fullPath: '/demo/realestate'
      preLoaderRoute: typeof DemoRealestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/health': {
      id: '/demo/health'
      path: '/demo/health'
      fullPath: '/demo/health'
      preLoaderRoute: typeof DemoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/gallery': {
      id: '/demo/gallery'
      path: '/demo/gallery'
      fullPath: '/demo/gallery'
      preLoaderRoute: typeof DemoGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/fitness': {
      id: '/demo/fitness'
      path: '/demo/fitness'
      fullPath: '/demo/fitness'
      preLoaderRoute: typeof DemoFitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/education': {
      id: '/demo/education'
      path: '/demo/education'
      fullPath: '/demo/education'
      preLoaderRoute: typeof DemoEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ecommerce': {
      id: '/demo/ecommerce'
      path: '/demo/ecommerce'
      fullPath: '/demo/ecommerce'
      preLoaderRoute: typeof DemoEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoEcommerceRoute: DemoEcommerceRoute,
  DemoEducationRoute: DemoEducationRoute,
  DemoFitnessRoute: DemoFitnessRoute,
  DemoGalleryRoute: DemoGalleryRoute,
  DemoHealthRoute: DemoHealthRoute,
  DemoRealestateRoute: DemoRealestateRoute,
  DemoRestaurantRoute: DemoRestaurantRoute,
  DemoSalonRoute: DemoSalonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
